"use client";

import { cn } from "@/lib/utils";

const SECTIONS = [
  { key: "headline", label: "Headline", icon: "H" },
  { key: "about", label: "About Section", icon: "A" },
  { key: "skills", label: "Skills", icon: "S" },
  { key: "experience", label: "Experience", icon: "E" },
] as const;

interface GenerationProgressProps {
  /** Raw text accumulated so far from the stream */
  streamedText: string;
  /** Whether the stream has completed */
  isComplete: boolean;
  /** Error message if generation failed */
  error: string | null;
}

export function GenerationProgress({
  streamedText,
  isComplete,
  error,
}: GenerationProgressProps) {
  // Estimate which sections have been generated by checking for JSON keys
  const hasSection = (key: string) =>
    streamedText.includes(`"${key}"`);

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-3">
        {!isComplete && !error && (
          <div className="h-5 w-5 animate-spin rounded-full border-2 border-muted-foreground border-t-primary" />
        )}
        <h3 className="text-lg font-semibold">
          {error
            ? "Generation Failed"
            : isComplete
              ? "Draft Ready"
              : "Generating your optimized profile..."}
        </h3>
      </div>

      {error && (
        <div className="rounded-lg border border-red-200 bg-red-50 p-4 dark:border-red-900 dark:bg-red-950">
          <p className="text-sm text-red-800 dark:text-red-200">{error}</p>
        </div>
      )}

      <div className="grid gap-2 sm:grid-cols-2">
        {SECTIONS.map((section) => {
          const done = hasSection(section.key);
          const active = !done && !isComplete && !error;

          return (
            <div
              key={section.key}
              className={cn(
                "flex items-center gap-3 rounded-lg border p-3 transition-colors",
                done && "border-emerald-200 bg-emerald-50 dark:border-emerald-900 dark:bg-emerald-950",
                active && "border-primary/50 bg-primary/5",
                !done && !active && "opacity-50"
              )}
            >
              <div
                className={cn(
                  "flex h-8 w-8 items-center justify-center rounded-full text-sm font-bold",
                  done && "bg-emerald-100 text-emerald-700 dark:bg-emerald-900 dark:text-emerald-300",
                  active && "bg-primary/10 text-primary",
                  !done && !active && "bg-muted text-muted-foreground"
                )}
              >
                {done ? (
                  <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                  </svg>
                ) : (
                  section.icon
                )}
              </div>
              <div className="flex-1">
                <p className={cn("text-sm font-medium", done && "text-emerald-800 dark:text-emerald-200")}>
                  {section.label}
                </p>
                {active && (
                  <p className="text-xs text-muted-foreground">Generating...</p>
                )}
              </div>
            </div>
          );
        })}
      </div>

      {/* Streaming text preview */}
      {!isComplete && !error && streamedText.length > 0 && (
        <div className="max-h-32 overflow-hidden rounded-lg border bg-muted/30 p-3">
          <p className="font-mono text-xs text-muted-foreground line-clamp-4 whitespace-pre-wrap">
            {streamedText.slice(-300)}
          </p>
          <div className="mt-1 h-4 bg-gradient-to-t from-muted/30 to-transparent" />
        </div>
      )}
    </div>
  );
}
